# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'QTermLinks.ui'
#
# Created: Thu Sep 18 09:31:32 2014
#      by: PyQt5 UI code generator 5.3.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_QTermLinks(object):
    def setupUi(self, QTermLinks):
        QTermLinks.setObjectName("QTermLinks")
        QTermLinks.resize(520, 166)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(QTermLinks.sizePolicy().hasHeightForWidth())
        QTermLinks.setSizePolicy(sizePolicy)
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(QTermLinks)
        self.horizontalLayout_4.setSpacing(0)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.groupBoxTermLinker = QtWidgets.QGroupBox(QTermLinks)
        self.groupBoxTermLinker.setMaximumSize(QtCore.QSize(16777215, 200))
        self.groupBoxTermLinker.setBaseSize(QtCore.QSize(0, 100))
        self.groupBoxTermLinker.setObjectName("groupBoxTermLinker")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.groupBoxTermLinker)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.tableWidget = QtWidgets.QTableWidget(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tableWidget.sizePolicy().hasHeightForWidth())
        self.tableWidget.setSizePolicy(sizePolicy)
        self.tableWidget.setAutoFillBackground(True)
        self.tableWidget.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tableWidget.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.tableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tableWidget.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tableWidget.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.tableWidget.setShowGrid(False)
        self.tableWidget.setGridStyle(QtCore.Qt.DashLine)
        self.tableWidget.setCornerButtonEnabled(True)
        self.tableWidget.setRowCount(3)
        self.tableWidget.setColumnCount(4)
        self.tableWidget.setObjectName("tableWidget")
        self.tableWidget.horizontalHeader().setVisible(False)
        self.tableWidget.horizontalHeader().setStretchLastSection(True)
        self.tableWidget.verticalHeader().setVisible(False)
        self.tableWidget.verticalHeader().setDefaultSectionSize(20)
        self.verticalLayout_2.addWidget(self.tableWidget)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelKeys = QtWidgets.QLabel(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.labelKeys.sizePolicy().hasHeightForWidth())
        self.labelKeys.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setBold(False)
        font.setWeight(50)
        self.labelKeys.setFont(font)
        self.labelKeys.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.labelKeys.setObjectName("labelKeys")
        self.horizontalLayout_2.addWidget(self.labelKeys)
        self.keyTableWidget = QtWidgets.QTableWidget(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.keyTableWidget.sizePolicy().hasHeightForWidth())
        self.keyTableWidget.setSizePolicy(sizePolicy)
        self.keyTableWidget.setMaximumSize(QtCore.QSize(16777215, 30))
        self.keyTableWidget.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.keyTableWidget.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.keyTableWidget.setShowGrid(False)
        self.keyTableWidget.setWordWrap(False)
        self.keyTableWidget.setCornerButtonEnabled(False)
        self.keyTableWidget.setObjectName("keyTableWidget")
        self.keyTableWidget.setColumnCount(0)
        self.keyTableWidget.setRowCount(0)
        self.keyTableWidget.horizontalHeader().setVisible(False)
        self.keyTableWidget.verticalHeader().setVisible(False)
        self.horizontalLayout_2.addWidget(self.keyTableWidget)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.verticalLayout_2.addLayout(self.horizontalLayout_2)
        self.horizontalLayout.addLayout(self.verticalLayout_2)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.buttonLinkTerms = QtWidgets.QPushButton(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonLinkTerms.sizePolicy().hasHeightForWidth())
        self.buttonLinkTerms.setSizePolicy(sizePolicy)
        self.buttonLinkTerms.setObjectName("buttonLinkTerms")
        self.verticalLayout.addWidget(self.buttonLinkTerms)
        self.buttonUnlinkTerms = QtWidgets.QPushButton(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonUnlinkTerms.sizePolicy().hasHeightForWidth())
        self.buttonUnlinkTerms.setSizePolicy(sizePolicy)
        self.buttonUnlinkTerms.setObjectName("buttonUnlinkTerms")
        self.verticalLayout.addWidget(self.buttonUnlinkTerms)
        self.buttonAddFile = QtWidgets.QPushButton(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonAddFile.sizePolicy().hasHeightForWidth())
        self.buttonAddFile.setSizePolicy(sizePolicy)
        self.buttonAddFile.setLocale(QtCore.QLocale(QtCore.QLocale.English, QtCore.QLocale.UnitedKingdom))
        self.buttonAddFile.setObjectName("buttonAddFile")
        self.verticalLayout.addWidget(self.buttonAddFile)
        self.buttonRemoveFiles = QtWidgets.QPushButton(self.groupBoxTermLinker)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonRemoveFiles.sizePolicy().hasHeightForWidth())
        self.buttonRemoveFiles.setSizePolicy(sizePolicy)
        self.buttonRemoveFiles.setObjectName("buttonRemoveFiles")
        self.verticalLayout.addWidget(self.buttonRemoveFiles)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.gridLayout_2.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.horizontalLayout_4.addWidget(self.groupBoxTermLinker)

        self.retranslateUi(QTermLinks)
        QtCore.QMetaObject.connectSlotsByName(QTermLinks)

    def retranslateUi(self, QTermLinks):
        _translate = QtCore.QCoreApplication.translate
        QTermLinks.setWindowTitle(_translate("QTermLinks", "Term linker"))
        self.groupBoxTermLinker.setTitle(_translate("QTermLinks", "Related things"))
        self.tableWidget.setSortingEnabled(False)
        self.labelKeys.setText(_translate("QTermLinks", "Key: "))
        self.buttonLinkTerms.setText(_translate("QTermLinks", "&Link terms"))
        self.buttonUnlinkTerms.setText(_translate("QTermLinks", "&Unlink terms"))
        self.buttonAddFile.setText(_translate("QTermLinks", "&Add files"))
        self.buttonRemoveFiles.setText(_translate("QTermLinks", "&Remove files"))

